### ISSUE TITLE
Buildtime error - Can't resolve 'css/tailwind-css/tailwind.generated.css'

### ISSUE THREAD

**Issue by okezieuc** [codex-src/codex-wysiwyg#11]
@zaydek 
I cloned this repo to my local computer and installed dependencies with `yarn`.
Afterwards, I ran `yarn start` to begin the development server but it failed to compile with the following error message.

Error message
./src/index.js
Module not found: Can't resolve 'css/tailwind-css/tailwind.generated.css' in 'user\codex-wysiwyg\src'.

**Comment by zaydek** [comment]
Ah so sorry about that. This is because Tailwind needs to build ahead-of-time in order for anything to work. Try `tailwind-start` _first_, and then the normal commands. 👍

This is still a highly experimental project, by the way. 😭

**Comment by okezieuc** [comment]
@zaydek  I was able to build the css by first renaming `tailwind-defaultVariants.js` in the root folder to `defaultVariants.js` and running `npx tailwindcss build -c tailwind.config.js -o tailwind.generated.css` and finally copying that file to 'css/tailwind-css/'.

But when I did yarn start, what I had did not look like what I saw on the demo. I still had an editor with support for shorcuts like Ctrl+B but it didn't have the toolbar at the bottom. Is it that I made a mistake while building the CSS or there is a prop that I have to pass to `<EditorApp />` to enable some of the extra features.

**Comment by zaydek** [comment]
Sorry about that! I realized what’s going on. I started experimenting with another idea — try reverting to this commit [`b1f2d34c57ef0677ba0575178e15750103ac2ac6`](https://github.com/codex-src/codex-wysiwyg/commit/b1f2d34c57ef0677ba0575178e15750103ac2ac6).

Let me know if that works for you. 😅

**Comment by okezieuc** [comment]
It works when I reverted to that commit but I still had to copy the `tailwind.generated.css` to the node_modules folder.
But it all works well now
